[package]
name = "chiffre"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.12"
aes-gcm = "0.9.4"
rsa = "0.5.0"
rand = "0.8.4"