[package]
name = "xifrar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.12", features = ["derive"] }
openssl = "0.10.38"
rsa = "0.5.0"
rand = "0.8.4"